### ISSUE TITLE
trigrambot: fails to start if previous state exists

### ISSUE THREAD

**Issue by magsol** [magsol/pybot#7]
A `KeyError` is thrown when attempting to start TrigramBot after stopping it; if the .pkl state file is deleted, startup proceeds normally.

**Comment by magsol** [comment]
```
Traceback (most recent call last):
  File "trigrambot.py", line 150, in <module>
    bot.run()
  File "/pybot/pybot/pybot.py", line 242, in run
    getattr(self, '_handle_%s' % action)()
  File "/pybot/pybot.py", line 383, in _handle_tweet
    self.on_tweet()
  File "trigrambot.py", line 119, in on_tweet
    nextToken = model[key][np.random.randint(0, len(model[key]))]
KeyError: ('_START1_', '_START2_')
```

The `model` dictionary is empty; even though it proceeds through an initialization just before this, there are no tweets in the buffer so the model remains empty. Tweets are not saved to the local state, as this would potentially be a huge file i/o bottleneck for saving/loading previous state.

Another fix would be to explicitly set action wait times at the _start_ of the loop in `PyBot.run()`, rather than occurring only after the action has been executed. This presents an initialization problem wherein, upon start-up, all registered actions initially fire, but some may depend on other actions running first for some arbitrary period of time.
